"""initial schema

Revision ID: eec8b3f2b10e
Revises: 
Create Date: 2026-09-21 21:50:33.972988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eec8b3f2b10e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chain_loan_id', sa.BigInteger(), nullable=False),
    sa.Column('lender_address', sa.String(length=42), nullable=False),
    sa.Column('borrower_address', sa.String(length=42), nullable=False),
    sa.Column('principal_wei', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('collateral_wei', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('interest_bps', sa.BigInteger(), nullable=False),
    sa.Column('maturity_ts', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('principal_deposited', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('collateral_deposited', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('claimable_lender_wei', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('claimable_borrower_wei', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('create_tx_hash', sa.String(length=80), nullable=True),
    sa.Column('last_sync_tx_hash', sa.String(length=80), nullable=True),
    sa.Column('raw_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('claimable_borrower_wei >= 0', name='ck_loans_claimable_borrower_nonneg'),
    sa.CheckConstraint('claimable_lender_wei >= 0', name='ck_loans_claimable_lender_nonneg'),
    sa.CheckConstraint('collateral_deposited >= 0', name='ck_loans_collateral_dep_nonneg'),
    sa.CheckConstraint('collateral_wei >= 0', name='ck_loans_collateral_nonneg'),
    sa.CheckConstraint('principal_deposited >= 0', name='ck_loans_principal_dep_nonneg'),
    sa.CheckConstraint('principal_wei >= 0', name='ck_loans_principal_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_borrower_address'), 'loans', ['borrower_address'], unique=False)
    op.create_index('ix_loans_borrower_status', 'loans', ['borrower_address', 'status'], unique=False)
    op.create_index(op.f('ix_loans_chain_loan_id'), 'loans', ['chain_loan_id'], unique=True)
    op.create_index(op.f('ix_loans_lender_address'), 'loans', ['lender_address'], unique=False)
    op.create_index('ix_loans_lender_status', 'loans', ['lender_address', 'status'], unique=False)
    op.create_index(op.f('ix_loans_status'), 'loans', ['status'], unique=False)
    op.create_table('nonces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nonces_address'), 'nonces', ['address'], unique=False)
    op.create_index('ix_nonces_address_used', 'nonces', ['address', 'used_at'], unique=False)
    op.create_index(op.f('ix_nonces_nonce'), 'nonces', ['nonce'], unique=True)
    op.create_table('rate_limit_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('covenant_id', sa.BigInteger(), nullable=False),
    sa.Column('window_bucket', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_rate_limit_addr_cov_window', 'rate_limit_counters', ['address', 'covenant_id', 'window_bucket'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_address'), 'sessions', ['address'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_table('sync_cursor',
    sa.Column('shard_key', sa.String(length=64), nullable=False),
    sa.Column('last_synced_loan_id', sa.BigInteger(), nullable=False),
    sa.Column('last_synced_block', sa.BigInteger(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=2048), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('shard_key')
    )
    op.create_table('covenants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chain_covenant_id', sa.BigInteger(), nullable=False),
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('chain_loan_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.Enum('onchain', 'offchain', name='source_type_enum'), nullable=False),
    sa.Column('source_ref', sa.String(length=2048), nullable=False),
    sa.Column('condition_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consequence_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('challenge_window_seconds', sa.BigInteger(), nullable=False),
    sa.Column('raw_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_covenants_chain_covenant_id'), 'covenants', ['chain_covenant_id'], unique=True)
    op.create_index(op.f('ix_covenants_chain_loan_id'), 'covenants', ['chain_loan_id'], unique=False)
    op.create_index(op.f('ix_covenants_loan_id'), 'covenants', ['loan_id'], unique=False)
    op.create_index('ix_covenants_loan_source', 'covenants', ['loan_id', 'source_type'], unique=False)
    op.create_table('checks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chain_check_id', sa.BigInteger(), nullable=False),
    sa.Column('covenant_id', sa.BigInteger(), nullable=False),
    sa.Column('chain_covenant_id', sa.BigInteger(), nullable=False),
    sa.Column('chain_loan_id', sa.BigInteger(), nullable=False),
    sa.Column('triggered_by', sa.String(length=42), nullable=False),
    sa.Column('pinned_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='{hash, url_or_ref, block, timestamp}'),
    sa.Column('validator_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'compliant', 'breach', 'inconclusive', name='check_status_enum'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['covenant_id'], ['covenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checks_chain_check_id'), 'checks', ['chain_check_id'], unique=True)
    op.create_index(op.f('ix_checks_chain_covenant_id'), 'checks', ['chain_covenant_id'], unique=False)
    op.create_index(op.f('ix_checks_chain_loan_id'), 'checks', ['chain_loan_id'], unique=False)
    op.create_index(op.f('ix_checks_covenant_id'), 'checks', ['covenant_id'], unique=False)
    op.create_index('ix_checks_covenant_status', 'checks', ['covenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_checks_status'), 'checks', ['status'], unique=False)
    op.create_index(op.f('ix_checks_triggered_by'), 'checks', ['triggered_by'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('check_id', sa.BigInteger(), nullable=False),
    sa.Column('chain_check_id', sa.BigInteger(), nullable=False),
    sa.Column('submitted_by', sa.String(length=42), nullable=False),
    sa.Column('evidence_ref', sa.String(length=2048), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_chain_check_id'), 'challenges', ['chain_check_id'], unique=False)
    op.create_index(op.f('ix_challenges_check_id'), 'challenges', ['check_id'], unique=False)
    op.create_index(op.f('ix_challenges_submitted_by'), 'challenges', ['submitted_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenges_submitted_by'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_check_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_chain_check_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_checks_triggered_by'), table_name='checks')
    op.drop_index(op.f('ix_checks_status'), table_name='checks')
    op.drop_index('ix_checks_covenant_status', table_name='checks')
    op.drop_index(op.f('ix_checks_covenant_id'), table_name='checks')
    op.drop_index(op.f('ix_checks_chain_loan_id'), table_name='checks')
    op.drop_index(op.f('ix_checks_chain_covenant_id'), table_name='checks')
    op.drop_index(op.f('ix_checks_chain_check_id'), table_name='checks')
    op.drop_table('checks')
    op.drop_index('ix_covenants_loan_source', table_name='covenants')
    op.drop_index(op.f('ix_covenants_loan_id'), table_name='covenants')
    op.drop_index(op.f('ix_covenants_chain_loan_id'), table_name='covenants')
    op.drop_index(op.f('ix_covenants_chain_covenant_id'), table_name='covenants')
    op.drop_table('covenants')
    op.drop_table('sync_cursor')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_address'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ux_rate_limit_addr_cov_window', table_name='rate_limit_counters')
    op.drop_table('rate_limit_counters')
    op.drop_index(op.f('ix_nonces_nonce'), table_name='nonces')
    op.drop_index('ix_nonces_address_used', table_name='nonces')
    op.drop_index(op.f('ix_nonces_address'), table_name='nonces')
    op.drop_table('nonces')
    op.drop_index(op.f('ix_loans_status'), table_name='loans')
    op.drop_index('ix_loans_lender_status', table_name='loans')
    op.drop_index(op.f('ix_loans_lender_address'), table_name='loans')
    op.drop_index(op.f('ix_loans_chain_loan_id'), table_name='loans')
    op.drop_index('ix_loans_borrower_status', table_name='loans')
    op.drop_index(op.f('ix_loans_borrower_address'), table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###
